### ISSUE TITLE
lsrole and showrole is not working

### ISSUE THREAD

**Issue by unai-ttxu** [mlorenzo-stratio/vcli#21] opened 2019-03-28 09:38 UTC
Hi!

When trying to list roles and show an existing role, we got the following error:

```
[429] vcli@vault.service."paas.labs.stratio.com":8200 > lsrole
jq: error (at <stdin>:5): Cannot iterate over null (null)
```

This happens with version 0.5.12.

**Comment by ml0renz0** [comment] 2019-03-29 07:11
It seems I cannot reproduce this issue:
```
[200] vcli@gosec1.stratio.labs.com:8200 > lsrole
open
tais
vault-bkp
[200] vcli@gosec1.stratio.labs.com:8200 > showrole vault-bkp
vault-bkp
[200] vcli@gosec1.stratio.labs.com:8200 > lspol
default
fabric
gosec-sso
marathon
metronome
open
orchestrator-bkp
tais
vault-bkp
root
[200] vcli@gosec1.stratio.labs.com:8200 > showpol metronome
path "sys/*" {capabilities = ["deny"] }
 path "/auth/approle/*" {capabilities = ["read", "list", "create", "update"] }
```

**Comment by ml0renz0** [comment] 2019-04-23 08:27
It seems it didn't reproduce. We'll close it for the moment

**Closed as completed by ml0renz0** 2019-04-23 08:27 UTC
